language: cpp

compiler: gcc

cache:
  directories:
    - /home/travis/build/

jobs:
  include:
    - stage: Test
      script:
        - pip install --user cpplint
        - make test
    - stage: Build
      script: make build
    - stage: Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: build/sleep
        skip_cleanup: true
        on:
          tags: true
