sudo: required

language: cpp

compiler: gcc

cache:
  directories:
    - /home/travis/build/

jobs:
  include:
    - stage: Test
      script:
        - sudo apt-get update -q
        - sudo apt-get install python3 python3-pip -y
        - sudo pip3 install cpplint
        - make test
    - stage: Build
      script: make build
    - stage: Release
      script: ls build && echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: build/sleep
        skip_cleanup: true
        on:
          tags: true
