sudo: required

language: python

python: 3.6

cache:
  directories:
    - /home/travis/build/

jobs:
  include:
    - stage: Test
      script:
        - sudo pip install cpplint
        - make test
    - stage: Build
      script: 
        - sudo apt-get update -qq
        - sudo apt-get install gcc -y
        - make build
    - stage: Release
      script: ls build && echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: build/sleep
        skip_cleanup: true
        on:
          tags: false
